# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextRecognitionOnDevice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextRecognitionOnDevice
  $RNFirebaseAsStaticFramework = true
pod 'GoogleMLKit/TextRecognition','2.2.0'

end
